namespace ParserGenerator
{
    public enum TokenKind
    {
        NAME,
        STRING,
        NUMBER,
        NEWLINE,
        ENDMARKER,
        WHITESPACE,
        OP,
        LPAREN,
        RPAREN,
        LSQUARE,
        RSQUARE,
        NULLTOKEN,
        COMMA,
        SEMICOLON,
        MINUS,
        SLASH,
        LESSTHAN,
        GREATERTHAN,
        EQUAL,
        DOT,
        PERCENT,
        LBRACE,
        RBRACE,
        TILDE,
        CIRCUMFLEX,
        AT
    }
}